### ISSUE TITLE
Hi,I have a error in run inference!

### ISSUE THREAD

**Issue by BCWang93** [ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018#6]
I get this error like this:
FileNotFoundError: [Errno 2] No such file or directory: '/home/a/Bcw_data/open-image-challenge/input/class-descriptions-boxable.csv'
I want to know the '.csv' is where.

**Comment by ZFTurbo** [comment]
You can download it from here:
https://storage.googleapis.com/openimages/v5/class-descriptions-boxable.csv

**Comment by BCWang93** [comment]
> You can download it from here:
> https://storage.googleapis.com/openimages/v5/class-descriptions-boxable.csv

Thank you very much!I want use this implement in the 2019 open images challenge.I want to try the result!Thank you for your help!

**Comment by BCWang93** [comment]
> You can download it from here:
> https://storage.googleapis.com/openimages/v5/class-descriptions-boxable.csv

when I use the test file to test trained model.why I get this?
/home/a/anaconda3/envs/bcw_env/lib/python3.6/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Proc 0 files...
Thank you !

**Comment by ZFTurbo** [comment]
Warning is ok. You have zero files in folder. Check if there are some JPGs available.

**Comment by BCWang93** [comment]
> Warning is ok. You have zero files in folder. Check if there are some JPGs available.

yes,I find a error in my test file!I have solved it!Thanks you very much!

**Comment by BCWang93** [comment]
> Warning is ok. You have zero files in folder. Check if there are some JPGs available.

Hi,this file is where I can download.Thanks!
'bbox_labels_600_hierarchy.json'

**Comment by BCWang93** [comment]
> Warning is ok. You have zero files in folder. Check if there are some JPGs available.

Excuse me ,I have this error like this
Traceback (most recent call last):
  File "create_higher_level_predictions_from_level_1_predictions_csv.py", line 89, in <module>
    return_only_new=True)
  File "create_higher_level_predictions_from_level_1_predictions_csv.py", line 79, in create_higher_level_classes_from_csv
    new_boxes = extend_boxes(boxes, d1, d2, parents, return_only_new)
  File "create_higher_level_predictions_from_level_1_predictions_csv.py", line 17, in extend_boxes
    for p in parents[class_name]:
KeyError: 'studio couch'
Do you know how can I solve it?Thanks!

**Comment by BCWang93** [comment]
> Warning is ok. You have zero files in folder. Check if there are some JPGs available.

Hi,I use this implement to test the open Image 2019,I use the resnet101 pretrained model you give,but I only get 0.03962 score in the kaggle.Do you know this is why?I think this is unnormaly!Thank you very much!

**Comment by BCWang93** [comment]
> Warning is ok. You have zero files in folder. Check if there are some JPGs available.

can you give me some advice to increase the performance?Thank you!

**Comment by ZFTurbo** [comment]
Typical errors:
1) Check preprocessing of images
2) Check min/max size of images
3) Check you read it BGR
Also reduce THR for predicted boxes

I propose to check score on validation as well.

**Comment by BCWang93** [comment]
@ZFTurbo， I use your code and the model to inference .I think it is not the data probleme ...Thanks！

**Comment by BCWang93** [comment]
> Typical errors:
> 
> 1. Check preprocessing of images
> 2. Check min/max size of images
> 3. Check you read it BGR
>    Also reduce THR for predicted boxes
> 
> I propose to check score on validation as well.

Thanks for your replay!I use the resnet101 inference model you give,but when I use the inference model to predict the test dataset 2019,I get the very low score 0.036.So,I want to know the model you give whether to use to predict the test dataset?Thank you very much!

**Comment by BCWang93** [comment]
> @ZFTurbo， I use your code and the model to inference .I think it is not the data probleme ...Thanks！

Btw,should I use the training model or the inference model to test the test dataset 2019?Thanks!

**Comment by ZFTurbo** [comment]
As I can see from LB you already solved the problem?

**Comment by BCWang93** [comment]
> As I can see from LB you already solved the problem?

Now,I am not sure the problem is where.But I am not use the file 'create_higher_level_predictions_from_level_1_predictions_csv.py' to expand the result.And I only use the origin result I get,the score is normaly!So I am not sure the problem is where?Btw,Thank you for your project,it helped me a lot!Thanks!

**Comment by RohitMidha23** [comment]
> You can download it from here:
> https://storage.googleapis.com/openimages/v5/class-descriptions-boxable.csv

Hey, @ZFTurbo  I'm getting a KeyError when I use this file. Is there any other version I can use?
