### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by ZenFSheng** [ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018#7]
Thanks for your sharing~
I try to run this model on open image 2019 test images, but I got this error and I cannot find why could it happen. Can you help me with this?

`Traceback (most recent call last):
  File "E:/Datasets/model/Keras-RetinaNet-for-Open-Images-Challenge-2018-master/retinanet_inference_example.py", line 194, in <module>
    get_retinanet_predictions_for_files(files_to_process, output_cache_directory, pretrained_model_path, backbone)
  File "E:/Datasets/model/Keras-RetinaNet-for-Open-Images-Challenge-2018-master/retinanet_inference_example.py", line 75, in get_retinanet_predictions_for_files
    boxes, scores, labels = model.predict_on_batch(image)
ValueError: not enough values to unpack (expected 3, got 2)
`

**Comment by ZFTurbo** [comment]
What model did you use? Is it for inference (_converted)?

**Comment by ZenFSheng** [comment]
> What model did you use? Is it for inference (_converted)?

I use the backbone of ResNet152 for model training, should use the inference model ?

**Comment by ZenFSheng** [comment]
> What model did you use? Is it for inference (_converted)?

Thank you for your answering ! I think I have found the solution~ ：)

**Comment by BCWang93** [comment]
> > What model did you use? Is it for inference (_converted)?
> 
> Thank you for your answering ! I think I have found the solution~ ：)

Hi,do you use this model to test 2019 dataset ,I also use inference model to test 2019 dataset,but I get low score 0.0396.how do you result performence?You are only one to join this challenge?Thanks!

**Comment by ZenFSheng** [comment]
> > > What model did you use? Is it for inference (_converted)?
> > 
> > 
> > Thank you for your answering ! I think I have found the solution~ ：)
> 
> Hi,do you use this model to test 2019 dataset ,I also use inference model to test 2019 dataset,but I get low score 0.0396.how do you result performence?You are only one to join this challenge?Thanks!



> > > What model did you use? Is it for inference (_converted)?
> > 
> > 
> > Thank you for your answering ! I think I have found the solution~ ：)
> 
> Hi,do you use this model to test 2019 dataset ,I also use inference model to test 2019 dataset,but I get low score 0.0396.how do you result performence?You are only one to join this challenge?Thanks!

If you use this model directly on the test set, your score is quite normal~
I run the Faster RCNN with inception-resnetv2 which has 0.58mAP on last year test set. But I only got a score of 0.07739. So I think the annotations of  this year is more than last year, if we can train the finetune the model with 2019 dataset, it could be  further better .
Besides, yep, I join the competition along, and I`m short of GPU resource that makes me could not have too many chances to try my idea.

**Comment by ZenFSheng** [comment]
> > > What model did you use? Is it for inference (_converted)?
> > 
> > 
> > Thank you for your answering ! I think I have found the solution~ ：)
> 
> Hi,do you use this model to test 2019 dataset ,I also use inference model to test 2019 dataset,but I get low score 0.0396.how do you result performence?You are only one to join this challenge?Thanks!

If you use this model directly on the test set, your score is quite normal~
I run the Faster RCNN with inception-resnetv2 which has 0.58mAP on last year test set. But I only got a score of 0.07739. So I think the annotations of this year is more than last year, if we can train the finetune the model with 2019 dataset, it could be further better .
Besides, yep, I join the competition along, and I`m short of GPU resource that makes me could not have too many chances to try my idea.

**Comment by BCWang93** [comment]
> > > > What model did you use? Is it for inference (_converted)?
> > > 
> > > 
> > > Thank you for your answering ! I think I have found the solution~ ：)
> > 
> > 
> > Hi,do you use this model to test 2019 dataset ,I also use inference model to test 2019 dataset,but I get low score 0.0396.how do you result performence?You are only one to join this challenge?Thanks!
> 
> If you use this model directly on the test set, your score is quite normal~
> I run the Faster RCNN with inception-resnetv2 which has 0.58mAP on last year test set. But I only got a score of 0.07739. So I think the annotations of this year is more than last year, if we can train the finetune the model with 2019 dataset, it could be further better .
> Besides, yep, I join the competition along, and I`m short of GPU resource that makes me could not have too many chances to try my idea.

Thank you for your replay! I am only one to join this competition.Because I have not enough disk to save the train dataset,so I am only use the trained model to test the test dataset 2019.But I have find a fun thing is,I get two result use the author give model.But,I get two result,one is 0.039 score,but another is normaly is 0.36.I am not sure the problem!Thank you !

**Comment by ZenFSheng** [comment]
> > > > > What model did you use? Is it for inference (_converted)?
> > > > 
> > > > 
> > > > Thank you for your answering ! I think I have found the solution~ ：)
> > > 
> > > 
> > > Hi,do you use this model to test 2019 dataset ,I also use inference model to test 2019 dataset,but I get low score 0.0396.how do you result performence?You are only one to join this challenge?Thanks!
> > 
> > 
> > If you use this model directly on the test set, your score is quite normal~
> > I run the Faster RCNN with inception-resnetv2 which has 0.58mAP on last year test set. But I only got a score of 0.07739. So I think the annotations of this year is more than last year, if we can train the finetune the model with 2019 dataset, it could be further better .
> > Besides, yep, I join the competition along, and I`m short of GPU resource that makes me could not have too many chances to try my idea.
> 
> Thank you for your replay! I am only one to join this competition.Because I have not enough disk to save the train dataset,so I am only use the trained model to test the test dataset 2019.But I have find a fun thing is,I get two result use the author give model.But,I get two result,one is 0.039 score,but another is normaly is 0.36.I am not sure the problem!Thank you !

Woh! That`s so interesting~ Did you use the resnet-101 backbone that getting the score of 0.36?

**Comment by BCWang93** [comment]
> > > > > > What model did you use? Is it for inference (_converted)?
> > > > > 
> > > > > 
> > > > > Thank you for your answering ! I think I have found the solution~ ：)
> > > > 
> > > > 
> > > > Hi,do you use this model to test 2019 dataset ,I also use inference model to test 2019 dataset,but I get low score 0.0396.how do you result performence?You are only one to join this challenge?Thanks!
> > > 
> > > 
> > > If you use this model directly on the test set, your score is quite normal~
> > > I run the Faster RCNN with inception-resnetv2 which has 0.58mAP on last year test set. But I only got a score of 0.07739. So I think the annotations of this year is more than last year, if we can train the finetune the model with 2019 dataset, it could be further better .
> > > Besides, yep, I join the competition along, and I`m short of GPU resource that makes me could not have too many chances to try my idea.
> > 
> > 
> > Thank you for your replay! I am only one to join this competition.Because I have not enough disk to save the train dataset,so I am only use the trained model to test the test dataset 2019.But I have find a fun thing is,I get two result use the author give model.But,I get two result,one is 0.039 score,but another is normaly is 0.36.I am not sure the problem!Thank you !
> 
> Woh! That`s so interesting~ Did you use the resnet-101 backbone that getting the score of 0.36?

Hi,guys!I see you in the kaggle!Can I join you team?Thanks!Btw,I use the resnet-101 and resnet-152 to ensemble result!I get the score 0.45 now.But I don't know how can I do next?So I want to join a team!Thanks!

**Comment by ZenFSheng** [comment]
Thank you for your invitation~  My wechat is 17640695696, we can communicate on wechat continuously~

**Comment by ZenFSheng** [comment]
> > > > > > > What model did you use? Is it for inference (_converted)?
> > > > > > 
> > > > > > 
> > > > > > Thank you for your answering ! I think I have found the solution~ ：)
> > > > > 
> > > > > 
> > > > > Hi,do you use this model to test 2019 dataset ,I also use inference model to test 2019 dataset,but I get low score 0.0396.how do you result performence?You are only one to join this challenge?Thanks!
> > > > 
> > > > 
> > > > If you use this model directly on the test set, your score is quite normal~
> > > > I run the Faster RCNN with inception-resnetv2 which has 0.58mAP on last year test set. But I only got a score of 0.07739. So I think the annotations of this year is more than last year, if we can train the finetune the model with 2019 dataset, it could be further better .
> > > > Besides, yep, I join the competition along, and I`m short of GPU resource that makes me could not have too many chances to try my idea.
> > > 
> > > 
> > > Thank you for your replay! I am only one to join this competition.Because I have not enough disk to save the train dataset,so I am only use the trained model to test the test dataset 2019.But I have find a fun thing is,I get two result use the author give model.But,I get two result,one is 0.039 score,but another is normaly is 0.36.I am not sure the problem!Thank you !
> > 
> > 
> > Woh! That`s so interesting~ Did you use the resnet-101 backbone that getting the score of 0.36?
> 
> Hi,guys!I see you in the kaggle!Can I join you team?Thanks!Btw,I use the resnet-101 and resnet-152 to ensemble result!I get the score 0.45 now.But I don't know how can I do next?So I want to join a team!Thanks!Btw,are you chinese?Can we exchange the wechat or other?Thanks!

Thank you for your invitation~ My wechat is 17640695696, we can communicate on wechat continuously~

**Comment by BCWang93** [comment]
> > > > > > > > What model did you use? Is it for inference (_converted)?
> > > > > > > 
> > > > > > > 
> > > > > > > Thank you for your answering ! I think I have found the solution~ ：)
> > > > > > 
> > > > > > 
> > > > > > Hi,do you use this model to test 2019 dataset ,I also use inference model to test 2019 dataset,but I get low score 0.0396.how do you result performence?You are only one to join this challenge?Thanks!
> > > > > 
> > > > > 
> > > > > If you use this model directly on the test set, your score is quite normal~
> > > > > I run the Faster RCNN with inception-resnetv2 which has 0.58mAP on last year test set. But I only got a score of 0.07739. So I think the annotations of this year is more than last year, if we can train the finetune the model with 2019 dataset, it could be further better .
> > > > > Besides, yep, I join the competition along, and I`m short of GPU resource that makes me could not have too many chances to try my idea.
> > > > 
> > > > 
> > > > Thank you for your replay! I am only one to join this competition.Because I have not enough disk to save the train dataset,so I am only use the trained model to test the test dataset 2019.But I have find a fun thing is,I get two result use the author give model.But,I get two result,one is 0.039 score,but another is normaly is 0.36.I am not sure the problem!Thank you !
> > > 
> > > 
> > > Woh! That`s so interesting~ Did you use the resnet-101 backbone that getting the score of 0.36?
> > 
> > 
> > Hi,guys!I see you in the kaggle!Can I join you team?Thanks!Btw,I use the resnet-101 and resnet-152 to ensemble result!I get the score 0.45 now.But I don't know how can I do next?So I want to join a team!Thanks!Btw,are you chinese?Can we exchange the wechat or other?Thanks!
> 
> Thank you for your invitation~ My wechat is 17640695696, we can communicate on wechat continuously~

好的。老铁，我已经加了你了。哈哈。谢谢！

**Comment by dongzhi0312** [comment]
两位老铁，你们在2019的训练集训练了吗，我运行 /train_oid_level_1_resnet101.py 时，遇到个问题，ModuleNotFoundError: No module named 'retinanet_training_level_1'

**Comment by RohitMidha23** [comment]
Hey @BCWang93  which model did you use to get 0.45 score?

**Comment by louielu1027** [comment]
@BCWang93 老铁，我想问一下，你没训练，直接拿这俩模型怼出了0.45？我在榜上看到你了，能分享一下咋搞得吗，我现在也没时间训练了。。。。
